version: "3.7"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - ./backups:/home/backups
    command: -p 5432
